window.UIRenderer = window.UIRenderer || {};

// Utility function for word forms
window.UIRenderer.getWordForm = function (n, textForms) {
    n = Math.abs(n) % 100;
    const n1 = n % 10;
    if (n > 10 && n < 20) return textForms[2];
    if (n1 > 1 && n1 < 5) return textForms[1];
    if (n1 === 1) return textForms[0];
    return textForms[2];
  };

// Common libraries database
window.UIRenderer.getCommonLibraries = function () {
    return {
      react: "Бібліотека для побудови користувацьких інтерфейсів від Facebook",
      "react-dom": "Рендер React у веб-додатках",
      "react-scripts": "Скрипти та конфігурація для Create React App",
      next: "React-фреймворк для продакшену (SSR, SSG, ISR)",
      gatsby: "Генератор статичних сайтів на React",
      vue: "Прогресивний JavaScript-фреймворк",
      nuxt: "Універсальний додаток на Vue.js",
      angular: "Платформа для веб-додатків",
      svelte: "Компілятор для реактивних інтерфейсів",
      redux: "Контейнер стану для JavaScript додатків",
      "react-redux": "Офіційний біндінг React для Redux",
      "@reduxjs/toolkit": "Офіційний набір інструментів для Redux",
      zustand: "Мінімалістичне сховище стану для React",
      mobx: "Бібліотека керування станом",
      recoil: "Бібліотека керування станом від Facebook",
      jotai: "Примітиви стану для React",
      valtio: "Просте керування станом з проксі",
      "@mui/material": "Бібліотека компонентів Material-UI",
      "@mui/icons-material": "Іконки Material Design",
      "@mui/lab": "Лабораторні компоненти Material-UI",
      "@mui/x-charts": "Графіки для MUI",
      "@mui/x-date-pickers": "Вибір дат для MUI",
      antd: "UI бібліотека Ant Design",
      "chakra-ui": "Простий, модульний та доступний UI-компонент",
      tailwindcss: "Утилітарний CSS фреймворк",
      bootstrap: "Популярний CSS фреймворк",
      "slick-carousel": "Адаптивний карусель слайдів",
      "react-slick": "React-компонент для каруселі slick",
      "react-hook-form": "Валідація форм з мінімальним рендерингом",
      formik: "Побудова форм у React",
      yup: "Схема валідації об'єктів",
      zod: "Схема валідації TypeScript-first",
      "@hookform/resolvers": "Інтеграція react-hook-form з валідаторами",
      axios: "HTTP клієнт для браузера та Node.js",
      "@apollo/client": "Клієнт для роботи з GraphQL",
      graphql: "Мова запитів для API",
      ky: "Мінімалістичний HTTP клієнт на основі Fetch",
      "react-query": "Керування серверним станом у React",
      "@tanstack/react-query": "Бібліотека для керування кешем даних",
      swr: "React Hooks для віддалених даних",
      dayjs: "Маленька альтернатива Moment.js",
      "date-fns": "Сучасна бібліотека для роботи з датами",
      luxon: "Бібліотека для роботи з датами та часом",
      moment: "Бібліотека для роботи з датами (застаріла)",
      i18next: "Фреймворк інтернаціоналізації",
      "react-i18next": "Інтеграція i18next з React",
      "react-intl": "Форматування дат, чисел та рядків",
      jest: "JavaScript-фреймворк для тестування",
      "@testing-library/react": "Інструменти тестування React-компонентів",
      cypress: "Фреймворк для e2e тестування",
      "react-testing-library": "Легковісні утиліти для тестування React",
      typescript: "Надбудова над JavaScript з типізацією",
      webpack: "Збірка модулів JavaScript",
      vite: "Швидка збірка для сучасного вебу",
      eslint: "Лінтер для JavaScript/TypeScript",
      prettier: "Форматувальник коду",
      lodash: "Утиліти для роботи з даними",
      clsx: "Утиліта для об'єднання класів",
      classnames: "Просте об'єднання класів",
      immer: "Незмінні структури даних",
      ramda: "Функційна бібліотека для JavaScript",
      "react-helmet": "Керування head документа",
      "react-dropzone": "Завантаження файлів з перетягуванням",
      "react-virtualized": "Ефективний рендеринг списків",
      "react-window": "Ефективний рендеринг списків (новіша версія)",
      recharts: "Бібліотека графіків на основі D3",
      apexcharts: "Сучасні інтерактивні графіки",
      d3: "Бібліотека для візуалізації даних",
      "auth0-js": "Аутентифікація з Auth0",
      firebase: "Платформа для веб-додатків від Google",
      "jwt-decode": "Декодування JWT токенів",
      stripe: "Інтеграція з платіжною системою Stripe",
      braintree: "Платіжний шлюз Braintree",
      leaflet: "Бібліотека інтерактивних карт",
      "google-maps-react": "Інтеграція Google Maps з React",
      "framer-motion": "Бібліотека анімацій для React",
      "react-spring": "Фізично реалістичні анімації",
      gsap: "Потужна бібліотека анімацій",
      storybook: "Інструмент для розробки UI компонентів",
      docusaurus: "Генератор документації",
      "redux-persist": "Збереження стану Redux у сховищі",
      localforage: "Покращений localStorage",
      "draft-js": "Фреймворк для створення текстових редакторів",
      "react-quill": "Потужний текстовий редактор",
      slate: "Повністю налаштовуваний фреймворк для текстових редакторів",
      "react-phone-number-input": "Введення номеру телефону з підтримкою країн",
      "libphonenumber-js": "Бібліотека для роботи з номерами телефонів",
      "react-country-flag": "Відображення прапорів країн",
      qrcode: "Генерація QR-кодів",
      "react-qr-code": "Компонент React для генерації QR-кодів",
      notistack: "Повідомлення та сповіщення",
      "react-toastify": "Тостери для сповіщень",
      "react-hot-toast": "Легкі гарячі сповіщення",
      "@tanstack/react-table": "Потужні таблиці з сортуванням та пагінацією",
      "react-data-table-component": "Гнучкий компонент таблиць даних",
      "material-table": "Таблиці даних для Material-UI",
      "file-saver": "Збереження файлів у браузері",
      xlsx: "Робота з Excel файлами",
      "pdf-lib": "Створення та редагування PDF",
      "@chakra-ui/react": "Простий, модульний та доступний компонентний набір",
      "shadcn/ui":
        "Компоненти UI, створені з використанням Radix UI та Tailwind CSS",
      daisyui: "Безкоштовна бібліотека компонентів для Tailwind CSS",
      headlessui: "Повністю нестилізовані, повністю доступні компоненти UI",
      "radix-ui":
        "Низькорівневі, нестилізовані компоненти для створення дизайн-систем",
      mantine: "Повноцінна бібліотека React-компонентів",
      xstate: "Бібліотека керування станом та автоматів станів",
      effector: "Ефективне керування станом",
      "mobx-state-tree": "Розширене керування станом з MobX",
      concent: "Прогресивне керування станом для React",
      rematch: "Фреймворк для Redux без шаблонного коду",
      formidable: "Валідація та обробка форм",
      "react-jsonschema-form": "Генерація форм з JSON Schema",
      uniforms: "React-бібліотека для створення форм з будь-якої схеми даних",
      "react-use-gesture": "Сучасні жести для React",
      "react-intersection-observer": "Відстеження видимості елементів",
      victory: "Компоненти для візуалізації даних для React",
      nivo: "Багатобічна бібліотека графіків на основі D3",
      visx: "Візуальні компоненти від Airbnb",
      echarts: "Потужна бібліотека для створення інтерактивних графіків",
      "react-leaflet": "React-компоненти для Leaflet",
      "google-map-react": "Інтеграція Google Maps з React",
      "deck.gl": "Візуалізація великих геопросторових даних",
      "mapbox-gl": "Інтерактивні карти з підтримкою векторних таліць",
      vitest: "Швидкий нативний тестовий фреймворк для Vite",
      playwright: "Надійне тестування для сучасних веб-додатків",
      msw: "API-мокінг для браузера та Node.js",
      "testing-library": "Сучасні API для тестування UI",
      esbuild: "Надшвидкий JavaScript бандлер",
      swc: "Швидкий компілятор JavaScript/TypeScript",
      rollup: "Модульний бандлер для JavaScript",
      parcel: "Нульова конфігурація веб-додатку",
      "react-native": "Фреймворк для створення нативних мобільних додатків",
      expo: "Набір інструментів для розробки React Native додатків",
      "react-native-web": "Запуск React Native компонентів у вебі",
      "react-native-paper": "Material Design для React Native",
      electron: "Побудова крос-платформових десктопних додатків",
      tauri: "Менші, швидкі настільні програми з веб-технологіями",
      "electron-builder": "Повний набір для пакування Electron-додатків",
      "wasm-pack": "Створення та публікація WebAssembly з Rust",
      emscripten: "Компіляція C/C++ у WebAssembly",
      assemblyscript: "TypeScript-подібна мова для WebAssembly",
      ethers: "Повна реалізація Ethereum Wallet",
      "web3.js": "Бібліотека для взаємодії з блокчейном Ethereum",
      wagmi: "React Hooks для Ethereum",
      viem: "Типобезпечний інтерфейс для Ethereum",
      "@clerk/clerk-react":
        "Сервіс аутентифікації та керування користувачами для React",
      "@react-oauth/google": "OAuth-авторизація через Google для React",
      "@emotion/react": "CSS-in-JS бібліотека для стилізації компонентів",
      "@emotion/styled": "Styled API для Emotion (CSS-in-JS)",
      "@eslint/js": "Офіційні базові правила ESLint",
      "eslint-plugin-react-hooks": "Правила ESLint для React Hooks",
      "eslint-plugin-react-refresh": "Підтримка Fast Refresh у React",
      "@tanstack/eslint-plugin-query": "ESLint правила для TanStack Query",
      "typescript-eslint": "ESLint інструменти для TypeScript",
      knip: "Аналіз невикористаних файлів, залежностей та експорту",
      globals: "Список глобальних змінних середовищ JavaScript",
      "@radix-ui/react-alert-dialog": "Модальне вікно попередження (Radix UI)",
      "@radix-ui/react-avatar": "Компонент аватара користувача",
      "@radix-ui/react-checkbox": "Доступний checkbox компонент",
      "@radix-ui/react-collapsible": "Компонент зі згортанням/розгортанням",
      "@radix-ui/react-dialog": "Доступний діалог (modal)",
      "@radix-ui/react-direction": "Утиліти напрямку LTR/RTL",
      "@radix-ui/react-dropdown-menu": "Dropdown меню",
      "@radix-ui/react-icons": "Іконки Radix UI",
      "@radix-ui/react-label": "Label для формових елементів",
      "@radix-ui/react-popover": "Popover компонент",
      "@radix-ui/react-radio-group": "Група радіо-кнопок",
      "@radix-ui/react-scroll-area": "Кастомний scrollbar",
      "@radix-ui/react-select": "Select компонент",
      "@radix-ui/react-separator": "Візуальний роздільник",
      "@radix-ui/react-slider": "Slider компонент",
      "@radix-ui/react-slot": "Композиція компонентів",
      "@radix-ui/react-switch": "Toggle switch",
      "@radix-ui/react-tabs": "Tabs компонент",
      "@radix-ui/react-tooltip": "Tooltip компонент",
      "@tanstack/react-query-devtools": "DevTools для TanStack Query",
      "@tanstack/react-router": "Типобезпечний роутер для React",
      "@tanstack/react-router-devtools": "DevTools для TanStack Router",
      "@tanstack/router-plugin": "Vite/Build плагін для TanStack Router",
      "@vitejs/plugin-react-swc": "SWC-плагін для швидкої збірки React у Vite",
      "@tailwindcss/vite": "Офіційний Tailwind CSS плагін для Vite",
      "@trivago/prettier-plugin-sort-imports":
        "Автоматичне сортування імпортів",
      "prettier-plugin-tailwindcss": "Сортування Tailwind-класів",
      "@types/node": "TypeScript типи для Node.js",
      "@types/react": "TypeScript типи для React",
      "@types/react-dom": "TypeScript типи для React DOM",
      "class-variance-authority": "Управління варіантами CSS-класів",
      cmdk: "Командна палітра (Command Menu) для React",
      "lucide-react": "Легка бібліотека SVG-іконок",
      sonner: "Toast-нотифікації від shadcn/ui",
      "tailwind-merge": "Обʼєднання Tailwind-класів без конфліктів",
      "tw-animate-css": "Готові анімації для Tailwind",
      "input-otp": "Ввід одноразових кодів (OTP)",
      "react-day-picker": "Календар та вибір дат для React",
      "react-google-charts": "Інтеграція Google Charts у React",
      "react-quill-new": "Оновлена версія Quill редактора для React",
      "react-top-loading-bar": "Індикатор завантаження зверху сторінки",
      "@faker-js/faker": "Генерація фейкових даних для тестування",
      "web-vitals": "Вимірювання продуктивності веб-додатку",
      sentry: "Моніторинг помилок у продакшені",
      dompurify: "Очищення HTML від XSS",
      bcryptjs: "Хешування паролів",
      "socket.io-client": "WebSocket клієнт для real-time додатків",
      "browser-image-compression": "Стиснення зображень у браузері",
      "react-player": "Вбудовування відео з YouTube, Vimeo тощо",
      nanoid: "Генерація коротких унікальних ID",
      "ts-pattern": "Pattern matching для TypeScript",
      "react-cookie": "Зручна робота з cookies у React",
      cookie: "Низькорівнева бібліотека для парсингу та серіалізації cookies",
      sass: "CSS препроцесор (SCSS/SASS)",
      postcss: "Інструмент для трансформації CSS за допомогою плагінів",
      "@tailwindcss/line-clamp":
        "Tailwind плагін для обмеження кількості рядків тексту",
      "react-icons": "Популярні іконки (FontAwesome, Material, etc.)",
      "@react-icons/all-files": "Оптимізовані іконки з tree-shaking",
      "hamburger-react": "Анімована hamburger-кнопка",
      "react-burgers": "Набір burger-кнопок для меню",
      "react-select": "Потужний select з пошуком та мультивибором",
      "react-range-slider-input": "Range slider компонент",
      "react-loader-spinner": "Готові спінери та лоадери",
      striptags: "Видалення HTML-тегів з рядків",
      "@types/react-slick": "Типи для react-slick",
    };
  };
